package-name: TSR.Highlight.Pattern
visual-name: TSR Highlight Pattern
destination-folder: Assets/VRLabs/Toony Standard Rebuild Modules/TSR Highlight Pattern
extra-generated-meta:
  - path: Assets/VRLabs
    guid: 652a1ba5b00554143bc9a76307dbc4e8
  - path: Assets/VRLabs/Toony Standard Rebuild Modules
    guid: d3d02b5b274410849ba3e6c360e2f005
  - path: Assets/VRLabs/Toony Standard Rebuild Modules/TSR Highlight Pattern
    guid: e8fd4f70c58aae540baba4eb7faf4814